### ISSUE TITLE
What is the main difference between oracle class and category agnostic?

### ISSUE THREAD

**Issue by shwoo93** [TAO-Dataset/tao#29]
Hello,

What is the main difference between the oracle class and the category agnostic evaluation?

Also, When running the category-agnostic evaluation, I also get index error in /tao/utils/evaluation.py", line 503.
```writer.writerow({'category_id': cat, 'ap': category_aps[i]})
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by achalddave** [comment]
Good question. Category agnostic assigns all groundtruth and predictions to a single "object" category, while "oracle class" assigns predictions to the best matching groundtruth.

Both options remove the impact of classification on the final metric. The major practical difference is that category agnostic is *not* averaged per class, but rather computes a single AP across all classes. This means it will be biased towards the frequent classes (e.g., person, car, etc.). By contrast, oracle class still computes AP per class and averages, so each class is treated equally. In this sense, oracle class allows you to answer the question: "What AP would my model get if classification was a solved problem?", while category agnostic answers the question "What AP would my model get if all objects belong to a 'generic' object class?"

In practice, the "category-agnostic" evaluation isn't particularly useful in TAO due to TAO's federated nature. I wouldn't rely on it for anything more than diagnostics, and we would not recommend reporting it in a paper. Class oracle, on the other hand, is a very meaningful metric, and can be reported meaningfully. 

Regarding the error message: As a result of the above, category agnostic is not thoroughly tested, but I will check why the above error shows up. My guess is that during category agnostic evaluation, the code should set `tao_eval.params.cat_ids` to a single element list (`[1]`) here https://github.com/TAO-Dataset/tao/blob/0eb9b3767d31b7d6fc0bcccfda3a24227c5bb7a7/tao/utils/evaluation.py#L499. I'll debug this and update it next time I am evaluating models on TAO. Thanks for the report!

Please let me know if you have any further questions, or if any of this doesn't make sense!

**Comment by shwoo93** [comment]
Thanks for your kind and detailed reply.

One more question, what factors are still penalized for the following each oracle metric?
Maybe...
- Oracle-class {tracking/association errors, false negatives}
- Oracle-track {classification errors, false negatives}
- Oracle-track_class {false negatives}

So, could we think that the performance differences between the ```Oracle-track_class and Oracle-class``` or ```Oracle-track_class and Oracle-track``` indicate there is a room for improvement **purely** by enhancing tracking and classificaiton ability, respectively?

**Comment by achalddave** [comment]
Thanks for the excellent questions.

1. Yes, the factors you listed are exactly correct. I believe your second statement regarding the performance differences indicating the tracking errors and classification errors is intuitively correct, but I would need to spend some more time on this to say whether it is exact (or if there are some edge cases). In general, the oracles suggest that performance on TAO can significantly improve by just fixing tracking and classification; the per-frame localization from the detector is pretty good already. 
2. Yes to both. In fact, we are discussing elevating the "oracle-class" evaluation to a primary "track" for TAO, to allow researchers to focus on tracking without worrying about classification.

**Comment by shwoo93** [comment]
Many thanks for your reply.
