### ISSUE TITLE
Track Visualization Codes

### ISSUE THREAD

**Issue by jainie0716** [TAO-Dataset/tao#30]
I want to see the tracking results.
Are there codes for visualizing the predicted tracklets?

**Comment by achalddave** [comment]
Sorry for the late reply, I somehow never got this notification. Thanks for bringing this up. There is a visualization script for the single object trackers [here](https://github.com/TAO-Dataset/tao/blob/master/scripts/trackers/single_obj/visualize.py). I'll dig up the visualization script for SORT later this week.

**Comment by achalddave** [comment]
I've added a script for visualizing the results of the SORT tracker here: https://github.com/TAO-Dataset/tao/blob/master/scripts/trackers/sort/visualize.py

Here's a sample command for running it:

```
python scripts/trackers/sort/visualize.py \
--track-result /path/to/dir_with_npz_from_track.py \
--frames-dir /path/to/tao/frames \
--annotations-json /path/to/tao/annotations  \
--output-dir output_dir
```

Note that this uses the .npz files output by [track.py](https://github.com/TAO-Dataset/tao/blob/master/scripts/trackers/sort/track.py) to create videos, so that it can output 30 fps videos (as opposed to the json files, which only contain results at 1fps).

Feel free to reopen if you have other questions, or file a new issue!
